name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/RELEASE'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pipe-cd/actions-gh-release@v2
        with:
          release_file: '**/RELEASE'
          token: ${{ secrets.GITHUB_TOKEN }}
